### ISSUE TITLE
Crash few seconds after startup

### ISSUE THREAD

**Issue by SirSpart** [johanneszab/TumblThree#323]
So i downloaded the latest release (8.63) and ran TumblThree.exe. For like 5-10 seconds no buttons and nothing is clickable, and then the application crashes,

Same issue as https://github.com/johanneszab/TumblThree/issues/311 and **does not seem like its fixed**.
I am running Windows 10.

**Comment by DigiHound** [comment]
Having a similar problem. Worked fine earlier, now crashing every single time it starts. Deleting all data in the AppData\Local\TumblThree directory has not worked. Running the compatibility troubleshooter has not worked. Completely deleting and unzipping the application for a second time has not worked. Rebooting has not worked. 

Despite the fact that I earlier had no trouble using TumblThree. 

Error message below: 

I get an Application Error and a Runtime Error. 

Application Error first. 

Faulting application name: TumblThree.exe, version: 1.0.8.64, time stamp: 0x5c0abf16
Faulting module name: KERNELBASE.dll, version: 10.0.17134.407, time stamp: 0x99042cc0
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x3a74
Faulting application start time: 0x01d48f25b1e0b445
Faulting application path: C:\Users\Alienware 13\Downloads\TumblThree-v1.0.8.64-Application\TumblThree\TumblThree.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fba86079-2b62-4f60-b21b-038dc7f1d504
Faulting package full name: 
Faulting package-relative application ID: 


Now the runtime error: 

Application: TumblThree.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Text.StringBuilder.AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
   at System.String.FormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
   at System.String.Format(System.IFormatProvider, System.String, System.Object)
   at TumblThree.Applications.Services.ConfirmTumblrPrivacyConsent+<ConfirmPrivacyConsentAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at TumblThree.Applications.Controllers.ModuleController+<Run>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at TumblThree.Presentation.App.Main()
